demo/examples/employees/urls.py
from django.conf.urls import url, include
from django.views import generic

from . import views


urlpatterns = [
    url('^$', generic.RedirectView.as_view(
        url='./departments/'), name="index"),
    url('^departments/', include(views.DepartmentViewSet().urls)),
    url('^employees/', include(views.EmployeeViewSet().urls)),
]

demo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.shortcuts import render
from django.views import generic, static

import debug_toolbar

from formtools.wizard.views import SessionWizardView
from material.frontend import urls as frontend_urls

from . import forms, widget_forms, admin_forms


def index_view(request):
    context = {
        'login': forms.LoginForm(),
        'registration': forms.RegistrationForm(),
        'checkout': forms.CheckoutForm(),
        'order': forms.OrderForm(),
        'comment': forms.CommentForm(),
        'bank': forms.BankForm(),
    }
    return render(request, 'index.html', context)


class Wizard(SessionWizardView):
    form_list = [forms.WizardForm1, forms.WizardForm2]

    def done(self, form_list, **kwargs):
        return render(self.request, 'formtools/wizard/wizard_done.html', {
            'form_data': [form.cleaned_data for form in form_list],
        })


class WidgetFormView(generic.FormView):
    template_name = 'widgets_demo.html'

    def form_valid(self, form):
        return self.render_to_response(
            self.get_context_data(form=form))


class AdminFormView(generic.FormView):
    template_name = 'admin_demo.html'

    @classmethod
    def as_view(cls, *args, **kwargs):
        return login_required(super(AdminFormView, cls).as_view(*args, **kwargs))

    def form_valid(self, form):
        return self.render_to_response(
            self.get_context_data(form=form))


urlpatterns = [
    url(r'^$', index_view),
    url(r'^__debug__/', include(debug_toolbar.urls)),

    # demo
    url(r'^demo/login/$', generic.FormView.as_view(
        form_class=forms.LoginForm, success_url='/demo/login/', template_name="demo.html")),
    url(r'^demo/registration/$', generic.FormView.as_view(
        form_class=forms.RegistrationForm, success_url='/demo/registration/', template_name="demo.html")),
    url(r'^demo/contact/$', generic.FormView.as_view(
        form_class=forms.ContactForm, success_url='/demo/contact/', template_name="demo.html")),
    url(r'^demo/order/$', generic.FormView.as_view(
        form_class=forms.OrderForm, success_url='/demo/order/', template_name="demo.html")),
    url(r'^demo/checkout/$', generic.FormView.as_view(
        form_class=forms.CheckoutForm, success_url='/demo/checkout/', template_name="demo.html")),
    url(r'^demo/comment/$', generic.FormView.as_view(
        form_class=forms.CommentForm, success_url='/demo/comment/', template_name="demo.html")),
    url(r'^demo/bank/$', generic.FormView.as_view(
        form_class=forms.BankForm, success_url='/demo/bank/', template_name="demo.html")),
    url(r'^demo/wizard/$', Wizard.as_view()),
    url(r'^foundation/basic/', generic.RedirectView.as_view(url='/?cache=no', permanent=False)),

    # core widgets test
    url(r'^demo/widget/$', generic.RedirectView.as_view(url='/demo/widget/boolean/', permanent=False)),
    url(r'^demo/widget/boolean/$', WidgetFormView.as_view(form_class=widget_forms.BooleanFieldForm)),
    url(r'^demo/widget/char/$', WidgetFormView.as_view(form_class=widget_forms.CharFieldForm)),
    url(r'^demo/widget/choice/$', WidgetFormView.as_view(form_class=widget_forms.ChoiceFieldForm)),
    url(r'^demo/widget/date/$', WidgetFormView.as_view(form_class=widget_forms.DateFieldForm)),
    url(r'^demo/widget/datetime/$', WidgetFormView.as_view(form_class=widget_forms.DateTimeFieldForm)),
    url(r'^demo/widget/decimal/$', WidgetFormView.as_view(form_class=widget_forms.DecimalFieldForm)),
    url(r'^demo/widget/duration/$', WidgetFormView.as_view(form_class=widget_forms.DurationFieldForm)),
    url(r'^demo/widget/email/$', WidgetFormView.as_view(form_class=widget_forms.EmailFieldForm)),
    url(r'^demo/widget/file/$', WidgetFormView.as_view(form_class=widget_forms.FileFieldForm)),
    url(r'^demo/widget/filepath/$', WidgetFormView.as_view(form_class=widget_forms.FilePathFieldForm)),
    url(r'^demo/widget/float/$', WidgetFormView.as_view(form_class=widget_forms.FloatFieldForm)),
    url(r'^demo/widget/image/$', WidgetFormView.as_view(form_class=widget_forms.ImageFieldForm)),
    url(r'^demo/widget/integer/$', WidgetFormView.as_view(form_class=widget_forms.IntegerFieldForm)),
    url(r'^demo/widget/ipaddress/$', WidgetFormView.as_view(form_class=widget_forms.GenericIPAddressFieldForm)),
    url(r'^demo/widget/multiplechoice/$', WidgetFormView.as_view(form_class=widget_forms.MultipleChoiceFieldForm)),
    url(r'^demo/widget/nullbolean/$', WidgetFormView.as_view(form_class=widget_forms.NullBooleanFieldForm)),
    url(r'^demo/widget/regex/$', WidgetFormView.as_view(form_class=widget_forms.RegexFieldForm)),
    url(r'^demo/widget/slug/$', WidgetFormView.as_view(form_class=widget_forms.SlugFieldForm)),
    url(r'^demo/widget/time/$', WidgetFormView.as_view(form_class=widget_forms.TimeFieldForm)),
    url(r'^demo/widget/url/$', WidgetFormView.as_view(form_class=widget_forms.URLFieldForm)),
    url(r'^demo/widget/uuid/$', WidgetFormView.as_view(form_class=widget_forms.UUIDField)),
    url(r'^demo/widget/combo/$', WidgetFormView.as_view(form_class=widget_forms.ComboFieldForm)),
    url(r'^demo/widget/splitdatetime/$', WidgetFormView.as_view(form_class=widget_forms.SplitDateTimeFieldForm)),
    url(r'^demo/widget/modelchoice/$', WidgetFormView.as_view(form_class=widget_forms.ModelChoiceFieldForm)),
    url(r'^demo/widget/modelmultichoice/$', WidgetFormView.as_view(form_class=widget_forms.ModelMultipleChoiceFieldForm)),

    url(r'^demo/widget/password/$', WidgetFormView.as_view(form_class=widget_forms.PasswordInputForm)),
    url(r'^demo/widget/hidden/$', WidgetFormView.as_view(form_class=widget_forms.HiddenInputForm)),
    url(r'^demo/widget/textarea/$', WidgetFormView.as_view(form_class=widget_forms.TextareaForm)),
    url(r'^demo/widget/radioselect/$', WidgetFormView.as_view(form_class=widget_forms.RadioSelectForm)),
    url(r'^demo/widget/checkboxmultiple/$', WidgetFormView.as_view(
        form_class=widget_forms.CheckboxSelectMultipleForm)),
    url(r'^demo/widget/fileinput/$', WidgetFormView.as_view(form_class=widget_forms.FileInputForm)),
    url(r'^demo/widget/splithiddendatetime/$', WidgetFormView.as_view(
        form_class=widget_forms.SplitHiddenDateTimeWidgetForm)),
    url(r'^demo/widget/selectdate/$', WidgetFormView.as_view(form_class=widget_forms.SelectDateWidgetForm)),

    # admin widgets test
    url(r'^demo/widget/admin/$', generic.RedirectView.as_view(
        url='/demo/widget/admin/filteredselectmultiple/', permanent=False)),
    url(r'^demo/widget/admin/filteredselectmultiple/$', AdminFormView.as_view(
        form_class=admin_forms.FilteredSelectMultipleForm)),
    url(r'^demo/widget/admin/admindatewidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminDateWidgetForm)),
    url(r'^demo/widget/admin/admintimewidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminTimeWidgetForm)),
    url(r'^demo/widget/admin/adminsplitdatetime/$', AdminFormView.as_view(
        form_class=admin_forms.AdminSplitDateTimeForm)),
    url(r'^demo/widget/admin/adminradioselect/$', AdminFormView.as_view(
        form_class=admin_forms.AdminRadioSelectForm)),
    url(r'^demo/widget/admin/adminfilewidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminFileWidgetForm)),
    url(r'^demo/widget/admin/foreignkeyrawidwidget/$', AdminFormView.as_view(
        form_class=admin_forms.ForeignKeyRawIdWidgetForm)),
    url(r'^demo/widget/admin/manytomanyrawidwidget/$', AdminFormView.as_view(
        form_class=admin_forms.ManyToManyRawIdWidgetForm)),
    url(r'^demo/widget/admin/relatedfieldwidgetwrapper/$', AdminFormView.as_view(
        form_class=admin_forms.RelatedFieldWidgetWrapperForm)),
    url(r'^demo/widget/admin/admintextareawidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminTextareaWidgetForm)),
    url(r'^demo/widget/admin/admintextinputwidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminTextInputWidgetForm)),
    url(r'^demo/widget/admin/adminemailfield/$', AdminFormView.as_view(
        form_class=admin_forms.AdminEmailFieldForm)),
    url(r'^demo/widget/admin/adminurlfieldwidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminURLFieldWidgetForm)),
    url(r'^demo/widget/admin/adminintegerfieldwidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminIntegerFieldWidgetForm)),
    url(r'^demo/widget/admin/adminbigintegerfieldwidget/$', AdminFormView.as_view(
        form_class=admin_forms.AdminBigIntegerFieldWidgetForm)),

    # frontend
    url(r'^frontend/$', generic.RedirectView.as_view(url='/frontend/accounting/', permanent=False), name="index"),
    url(r'', include(frontend_urls)),
]

urlpatterns += [
    url(r'^static/(?P<path>.*)$', static.serve,
        {'document_root': settings.STATIC_ROOT, 'show_indexes': True})
]

if 'material.frontend' not in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^admin/', include(admin.site.urls))]

if 'django.contrib.flatpages' in settings.INSTALLED_APPS:
    from django.contrib.flatpages import views
    urlpatterns += [url(r'^(?P<url>.*/)$', views.flatpage)]

demo/examples/employees/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from .managers import TemporalQuerySet


@python_2_unicode_compatible
class Department(models.Model):
    dept_no = models.CharField(_('code'), primary_key=True, max_length=4)
    dept_name = models.CharField(_('name'), unique=True, max_length=40)

    class Meta:
        verbose_name = _('department')
        verbose_name_plural = _('departments')
        db_table = 'departments'
        ordering = ['dept_no']

    def __str__(self):
        return self.dept_name


@python_2_unicode_compatible
class DeptEmp(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_no', verbose_name=_('department'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('department employee')
        verbose_name_plural = _('department employees')
        db_table = 'dept_emp'

    def __str__(self):
        return "{} - {}".format(self.employee, self.department)


@python_2_unicode_compatible
class DeptManager(models.Model):
    employee = models.ForeignKey('Employee', on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    department = models.ForeignKey(Department, on_delete=models.CASCADE, db_column='dept_no', verbose_name=_('department'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('department manager')
        verbose_name_plural = _('department managers')
        db_table = 'dept_manager'
        ordering = ['-from_date']

    def __str__(self):
        return "{} - {}".format(self.employee, self.department)


@python_2_unicode_compatible
class Employee(models.Model):
    emp_no = models.IntegerField(_('employee number'), primary_key=True)
    birth_date = models.DateField(_('birthday'))
    first_name = models.CharField(_('first name'), max_length=14)
    last_name = models.CharField(_('last name'), max_length=16)
    gender = models.CharField(_('gender'), max_length=1)
    hire_date = models.DateField(_('hire date'))

    class Meta:
        verbose_name = _('employee')
        verbose_name_plural = _('employees')
        db_table = 'employees'

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


@python_2_unicode_compatible
class Salary(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    salary = models.IntegerField(_('salary'))
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))

    objects = TemporalQuerySet.as_manager()

    class Meta:
        db_table = 'salaries'
        ordering = ['-from_date']
        verbose_name = _('salary')
        verbose_name_plural = _('salaries')

    def __str__(self):
        return "{} - {}".format(self.employee, self.salary)


@python_2_unicode_compatible
class Title(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, db_column='emp_no', verbose_name=_('employee'))
    title = models.CharField(_('title'), max_length=50)
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'), blank=True, null=True)

    objects = TemporalQuerySet.as_manager()

    class Meta:
        verbose_name = _('title')
        verbose_name_plural = _('titles')
        db_table = 'titles'

    def __str__(self):
        return "{} - {}".format(self.employee, self.title)

demo/examples/employees/views.py
import json
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.utils.translation import ugettext, ugettext_lazy as _

from material.frontend.views import ModelViewSet, ListModelView

from . import models, forms


@login_required
def change_manager(request, department_pk):
    department = get_object_or_404(models.Department, pk=department_pk)
    form = forms.ChangeManagerForm(department=department, data=request.POST or None)

    if form.is_valid():
        form.save()

    return render(request, 'employees/change_manager.html', {
        'form': form,
        'department': department,
        'model': models.Department
    })


@login_required
def change_salary(request, employee_pk):
    employee = get_object_or_404(models.Employee, pk=employee_pk)
    form = forms.ChangeSalaryForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()

    salaries = employee.salary_set.all().order_by('from_date')
    salary_data = {
        'labels': [salary.from_date.strftime('%Y-%m-%d') for salary in salaries],
        'datasets': [
            {'data': [salary.salary for salary in salaries], 'label': ugettext('Salary History')}
        ]
    }

    return render(request, 'employees/change_salary.html', {
        'form': form,
        'employee': employee,
        'salary_history': json.dumps(salary_data),
        'model': models.Employee
    })


@login_required
def change_title(request, employee_pk):
    employee = get_object_or_404(models.Employee, pk=employee_pk)
    form = forms.ChangeTitleForm(employee=employee, data=request.POST or None)

    if form.is_valid():
        form.save()

    return render(request, 'employees/change_title.html', {
        'form': form,
        'employee': employee,
        'model': models.Employee
    })


class DepartmentEmployesListView(ListModelView):
    model = models.Employee
    list_display = ('emp_no', 'first_name', 'last_name', 'current_salary')
    template_name = 'employees/department_employees.html'

    def get_queryset(self):
        today = timezone.now().date()
        department = get_object_or_404(models.Department, pk=self.kwargs['department_pk'])
        queryset = super(DepartmentEmployesListView, self).get_queryset()

        return queryset.filter(
            deptemp__department=department,
            deptemp__from_date__lte=today,
            deptemp__to_date__gt=today
        )

    def get_context_data(self, **kwargs):
        department = get_object_or_404(models.Department, pk=self.kwargs['department_pk'])
        return super(DepartmentEmployesListView, self).get_context_data(
            department=department, **kwargs)


class EmployeeViewSet(ModelViewSet):
    model = models.Employee
    list_display = ('emp_no', 'first_name', 'last_name', 'birth_date', 'current_salary')

    change_salary_view = [
        r'^(?P<employee_pk>.+)/change_salary/$',
        change_salary,
        '{model_name}_change_salary'
    ]

    change_title_view = [
        r'^(?P<employee_pk>.+)/change_title/$',
        change_title,
        '{model_name}_change_title'
    ]

    def current_salary(self, obj):
        salary = obj.salary_set.current()
        return salary.salary if salary is not None else 0
    current_salary.short_description = _('current salary')


class DepartmentViewSet(ModelViewSet):
    model = models.Department
    list_display = ('dept_no', 'dept_name', 'manager', 'employees')

    change_manager_view = [
        r'^(?P<department_pk>.+)/change_manager/$',
        change_manager,
        '{model_name}_change_manager'
    ]

    employees_list_view = [
        r'^(?P<department_pk>.+)/employees/$',
        DepartmentEmployesListView.as_view(viewset=EmployeeViewSet()),
        '{model_name}_employees'
    ]

    def manager(self, obj, today=None):
        if today is None:
            today = timezone.now().date()
        manager = obj.deptmanager_set.filter(
            from_date__lte=today,
            to_date__gt=today
        ).first()
        return manager.employee if manager is not None else ''

    def employees(self, obj):
        return obj.deptemp_set.count()
    employees.short_description = _('employees')

demo/examples/employees/templates/employees/base_module.html
{% extends 'material/frontend/base_module.html' %}

{% block js %}
{{ block.super }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
{% endblock %}

demo/examples/employees/templates/employees/change_manager.html
{% extends 'employees/base_module.html' %}
{% load i18n material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url department|frontend_urlname:'list' %}">{{ department|verbose_name_plural|title }}</a>
<a href="{% url department|frontend_urlname:'detail' department.pk %}">{{ department }}</a>
<a class="active">{% trans 'Change Manager' %}</a>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-content">
        {{ form }}
    </div>
</div>
{% endblock %}

demo/examples/employees/templates/employees/change_salary.html
{% extends 'employees/base_module.html' %}
{% load i18n material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url employee|frontend_urlname:'list' %}">{{ employee|verbose_name_plural|title }}</a>
<a href="{% url employee|frontend_urlname:'detail' employee.pk %}">{{ employee }}</a>
<a class="active">{% trans 'Change Salary' %}</a>
{% endblock %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">{% trans 'Salary History' %}</div>
            <canvas id="salaryChart" ></canvas>

            <script type="text/javascript">
              new Chart($("#salaryChart"), {
                type: 'line',
                data: {{ salary_history|safe }},
                options: {
                  scales: {
                    xAxes: [{
                      type: 'time',
                    }]
                  }
                }
              });
            </script>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <form method="POST">
            {% csrf_token %}
            <div class="card-content">
                {% form %}
                {% part form.salary prefix %}<i class="material-icons prefix">attach_money</i>{% endpart %}
                {% endform %}
            </div>
            <div class="card-action right-align">
                <button class=" btn" type="submit">{% trans 'Set new Salary' %}</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

demo/examples/employees/templates/employees/change_title.html
{% extends 'employees/base_module.html' %}
{% load i18n material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url employee|frontend_urlname:'list' %}">{{ employee|verbose_name_plural|title }}</a>
<a href="{% url employee|frontend_urlname:'detail' employee.pk %}">{{ employee }}</a>
<a class="active">{% trans 'Change Title' %}</a>
{% endblock %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <form method="POST">
            {% csrf_token %}
            <div class="card-content">
                <div class="card-title">{% trans 'Positions' %}</div>
                <table>
                    <thead>
                        <tr>
                            <td>{% trans 'Position' %}</td>
                            <td>{% trans 'Since' %}</td>
                            <td>{% trans 'To' %}</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for title in employee.title_set.all %}
                        <tr>
                            <td>{{ title.title }}</td>
                            <td>{{ title.from_date }}</td>
                            <td>{{ title.to_date }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {{ form }}
            </div>
            <div class="card-action right-align">
                <button type="submit" class="btn">{% trans 'Change' %}</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

demo/examples/employees/templates/employees/department_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            {% block card %}
            <div class="form-title">{{ view.model|verbose_name|title }}: {{ object }}</div>
            <table class="table bordered">
                {% for field_name, value in object_data %}
                <tr>
                    <th>{{ field_name }}</th>
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endblock %}
                <tr>
                    <th>Employees</th>
                    <td>
                        <a href="{% url 'employees:department_employees' object.pk %}">{{ object.deptemp_set.count }}</a>
                    </td>
                </tr>
            </table>
        </div>
        <div class="card-action">
            <div class="right-align">
                {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
                {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
            </div>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">{% trans 'Department Managers' %}</div>
            <table>
                <thead>
                    <tr>
                        <td>{% trans 'Manager' %}</td>
                        <td>{% trans 'Since' %}</td>
                    </tr>
                </thead>
                <tbody>
                    {% for manager in object.deptmanager_set.all %}
                    <tr>
                        <td>{{ manager.employee }}</td>
                        <td>{{ manager.from_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:department_change_manager' object.pk %}" class="btn disabled">{% trans 'Change' %}</a>
        </div>
    </div>
</div>
{% endblock %}

demo/examples/employees/templates/employees/department_employees.html
{% extends 'material/frontend/views/list.html' %}
{% load i18n material_frontend %}

{% block breadcrumbs_items %}
<a href="{% url department|frontend_urlname:'list' %}">{{ department|verbose_name_plural|title }}</a>
<a href="{% url department|frontend_urlname:'detail' department.pk %}">{{ department }}</a>
<a class="active">{% trans 'Employees' %}</a>
{% endblock %}

demo/examples/employees/templates/employees/employee_detail.html
{% extends 'material/frontend/views/detail.html' %}
{% load i18n material_frontend humanize %}

{% block content %}
<div class="left-panel">
    <div class="card">
        <div class="card-content">
            {% block card %}
            <div class="form-title">{{ view.model|verbose_name|title }}: {{ object }}</div>
            <table class="table bordered">
                {% for field_name, value in object_data %}
                <tr>
                    <th>{{ field_name }}</th>
                    <td>{{ value }}</td>
                    {% endfor %}
                </tr>
                {% endblock %}
            </table>
        </div>
        <div class="card-action">
            <div class="right-align">
                {% if delete_url %}<a class="waves-effect waves-light btn red white-text" href="{{ delete_url }}">{% trans 'Delete' %}</a>{% endif %}
                {% if change_url %}<a class="waves-effect waves-light btn white-text" href="{{ change_url }}">{% trans 'Change' %}</a>{% endif %}
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="card-title">{% trans 'Positions' %}</div>
            <table>
                <thead>
                    <tr>
                        <td>{% trans 'Position' %}</td>
                        <td>{% trans 'Since' %}</td>
                        <td>{% trans 'To' %}</td>
                    </tr>
                </thead>
                <tbody>
                    {% for title in object.title_set.all|slice:":10" %}
                    <tr>
                        <td>{{ title.title }}</td>
                        <td>{{ title.from_date }}</td>
                        <td>{{ title.to_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:employee_change_title' object.pk %}" class="btn">{% trans 'Change' %}</a>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="card-title">{% trans 'Departments' %}</div>
            <table>
                <thead>
                    <tr>
                        <td>{% trans 'Department' %}</td>
                        <td>{% trans 'Since' %}</td>
                        <td>{% trans 'To' %}</td>
                    </tr>
                </thead>
                <tbody>
                    {% for dept in object.deptemp_set.all|slice:":10" %}
                    <tr>
                        <td>{{ dept.department }}</td>
                        <td>{{ dept.from_date }}</td>
                        <td>{{ dept.to_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="right-panel">
    <div class="card">
        <div class="card-content">
            <div class="card-title">{% trans 'Salary' %}</div>
            <table>
                <thead>
                    <tr>
                        <td>{% trans 'Salary' %}</td>
                        <td>{% trans 'Since' %}</td>
                    </tr>
                </thead>
                <tbody>
                    {% for salary in object.salary_set.all|slice:":10" %}
                    <tr>
                        <td>${{ salary.salary|intcomma }}</td>
                        <td>{{ salary.from_date }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-action right-align">
            <a href="{% url 'employees:employee_change_salary' object.pk %}" class="btn">{% trans 'Change' %}</a>
        </div>
    </div>
</div>
{% endblock %}

demo/examples/employees/templates/employees/menu.html
{% load i18n %}
<ul>
    <li><a href="{% url 'employees:department_list' %}">{% trans 'Departments' %}</a></li>
    <li><a href="{% url 'employees:employee_list' %}">{% trans 'Employees' %}</a></li>
</ul>